### ISSUE TITLE
2.2.4 release broken

### ISSUE THREAD

**Issue by g-arjones** [rubyworks/xdg#7]
index.rb is missing from the released gem

```
irb(main):001:0> require 'xdg'
LoadError: cannot load such file -- /var/lib/gems/2.3.0/gems/xdg-2.2.4/lib/xdg/index
	from /var/lib/gems/2.3.0/gems/xdg-2.2.4/lib/xdg.rb:28:in `require_relative'
	from /var/lib/gems/2.3.0/gems/xdg-2.2.4/lib/xdg.rb:28:in `<module:XDG>'
	from /var/lib/gems/2.3.0/gems/xdg-2.2.4/lib/xdg.rb:26:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
```

**Comment by bkuhlmann** [comment]
🙇 @g-arjones. I recently took over this project and would encourage you to follow the issue here: https://github.com/bkuhlmann/xdg/issues/1. I'm going to close this in the meantime.

**Comment by g-arjones** [comment]
Thanks for the patch!
